title: Sajjad Hossain Talukder
description: Student, Premier University,Chittagong.
baseurl: "/resume/"
url: ""
photo_url: "my-photo.jpg"

# This is an optional section
# You can skip filling in one or more of the items in this section
email: "sajjadhossain.cse35@gmail.com"
linkedin: "https://www.linkedin.com/in/sajjad-hossain-talukder/"
github: "https://github.com/Sajjad-Hossain-Talukder"
# website: "http://tahanima.github.io/"
# medium: "https://tahanima.medium.com/"

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  
